name: Commit Checks
on:
  push:
    branches: [master, main, feat-*]
  pull_request:
    branches: [master, main, feat-*]
jobs:
  Pull-Request-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Deno v2.x
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task setup
      - run: deno lint
      - run: deno fmt --check
